/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mahasiswa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nursandi
 */
public class Form_Input_Mahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form Form_Input_Mahasiswa
     */
    public Form_Input_Mahasiswa() {
        initComponents();
        setLocationRelativeTo(null);
        load_table("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_NIM = new javax.swing.JTextField();
        B_Input = new javax.swing.JButton();
        B_Edit = new javax.swing.JButton();
        TF_Nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TF_NilaiHarian = new javax.swing.JTextField();
        B_Hapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TF_NilaiUTS = new javax.swing.JTextField();
        TF_NilaiUAS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TF_Cari = new javax.swing.JTextField();
        B_Cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Mahasiswa = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Input Nilai Mahasiswa");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Nilai Mahasiswa"));

        jLabel1.setText("NIM");

        B_Input.setText("Input");
        B_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_InputActionPerformed(evt);
            }
        });

        B_Edit.setText("Edit");
        B_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EditActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel6.setText("Nilai Harian");

        B_Hapus.setText("Hapus");
        B_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_HapusActionPerformed(evt);
            }
        });

        jLabel7.setText("Nilai UTS");

        jLabel8.setText("Nilai UAS");

        jLabel3.setText("40 %");

        jLabel4.setText("30 %");

        jLabel5.setText("30 %");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_NIM, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TF_NilaiHarian, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TF_NilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TF_NilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_Input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Hapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TF_NilaiHarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TF_NilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TF_NilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TF_NIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_Input))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TF_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_Edit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_Hapus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TF_Cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TF_CariKeyReleased(evt);
            }
        });

        B_Cari.setText("Cari");
        B_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CariActionPerformed(evt);
            }
        });

        Table_Mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "Nilai Harian", "Nilai UTS", "Nilai UAS", "Rata-Rata", "Hasil"
            }
        ));
        Table_Mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_MahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Mahasiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(TF_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B_Cari))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private static Connection hasilKoneksi;
    private ResultSet Rs;
    public static Connection koneksi() throws Exception{
        try {
            String url ="jdbc:mysql://localhost:3306/db_mahasiswa?zeroDateTimeBehavior=convertToNull";
            String user = "root";
            String pass = "";
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            hasilKoneksi=DriverManager.getConnection(url,user,pass);
        } catch (Exception e) {
            System.err.println("Koneksi Gagal = " + e.getMessage());
        }
        return hasilKoneksi;
    }
    
    public void SQL(String query){
        try {
            Connection conn = koneksi();
            PreparedStatement pst = conn.prepareStatement(query);
            pst.execute();
        } catch (Exception e) {
            System.err.println("Query Gagal = "+e.getMessage());
        }
    }
    
    public void read(String query){    
        try {
            Connection conn = koneksi();
            Statement Stm = conn.createStatement();
            Rs = Stm.executeQuery(query);
        } catch (Exception e) {
            System.err.println("Gagal Dibaca = " + e.getMessage());
        }
    }
    
    // Fungsi Untuk Menampilkan Data Kedalam Table
    private void load_table(String query){
        if(query.isEmpty()){
            query = "SELECT * FROM mahasiswa";
        }
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIM");
        model.addColumn("NAMA");
        model.addColumn("Nilai Harian");
        model.addColumn("Nilai UTS");
        model.addColumn("Nilau UAS");
        model.addColumn("Rata Rata");
        model.addColumn("Hasil");
        try {
            read(query);
            while (this.Rs.next()) {
               model.addRow(new Object[]{this.Rs.getString(2),this.Rs.getString(3),this.Rs.getString(4),this.Rs.getString(5),this.Rs.getString(6),this.Rs.getString(7),this.Rs.getString(8)});
            }
        } catch (Exception e) {
        }
        
        Table_Mahasiswa.setModel(model);
    }
    
    // Fungsi Untuk Mengosongkan Text field
    private void kosong(){
        TF_NIM.setText("");
        TF_Nama.setText("");
        TF_NilaiHarian.setText("");
        TF_NilaiUTS.setText("");
        TF_NilaiUAS.setText("");
        
    }
    
    int id;
    
    private void B_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_InputActionPerformed
        // TODO add your handling code here:
        String nim = TF_NIM.getText();
        String nama = TF_Nama.getText();
        int harian = Integer.parseInt(TF_NilaiHarian.getText());
        int uts = Integer.parseInt(TF_NilaiUTS.getText());
        int uas = Integer.parseInt(TF_NilaiUAS.getText());
        int rata_rata = (harian*40/100)+(uts*30/100)+(uas*30/100);
        String hasil = rata_rata > 60 ? "LULUS" : "TIDAK LULUS";
        SQL("INSERT INTO mahasiswa VALUES(DEFAULT,"+nim+",'"+nama+"',"+harian+","+uts+","+uas+","+rata_rata+",'"+hasil+"')");
        load_table("");
        kosong();
    }//GEN-LAST:event_B_InputActionPerformed

    private void Table_MahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_MahasiswaMouseClicked
        // TODO add your handling code here:
        int baris = Table_Mahasiswa.rowAtPoint(evt.getPoint());
        
        String nim = Table_Mahasiswa.getValueAt(baris, 0).toString();
        String nama = Table_Mahasiswa.getValueAt(baris, 1).toString();
        String harian = Table_Mahasiswa.getValueAt(baris, 2).toString();
        String uts = Table_Mahasiswa.getValueAt(baris, 3).toString();
        String uas = Table_Mahasiswa.getValueAt(baris, 4).toString();
        
        TF_NIM.setText(nim);
        TF_Nama.setText(nama);
        TF_NilaiHarian.setText(harian);
        TF_NilaiUTS.setText(uts);
        TF_NilaiUAS.setText(uas);
        try {
            read("SELECT ID FROM mahasiswa WHERE nim = "+nim+"");
            this.Rs.next();
            this.id = this.Rs.getInt(1);
        } catch (Exception e) {
            System.out.println("Error = "+e.getMessage());
        }
        
    }//GEN-LAST:event_Table_MahasiswaMouseClicked

    private void B_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EditActionPerformed
        // TODO add your handling code here:
        String nim = TF_NIM.getText();
        String nama = TF_Nama.getText();
        int harian = Integer.parseInt(TF_NilaiHarian.getText());
        int uts = Integer.parseInt(TF_NilaiUTS.getText());
        int uas = Integer.parseInt(TF_NilaiUAS.getText());
        int rata_rata = (harian*40/100)+(uts*30/100)+(uas*30/100);
        String hasil = rata_rata > 60 ? "LULUS" : "TIDAK LULUS";
        SQL("UPDATE mahasiswa SET NIM='"+nim+"',NAMA='"+nama+"',nilai_harian="+harian+",nilai_uts="+uts+",nilai_uas="+uas+",rata_rata="+rata_rata+",hasil='"+hasil+"' WHERE id ="+this.id+"");
        load_table("");
        kosong();
    }//GEN-LAST:event_B_EditActionPerformed

    private void B_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_HapusActionPerformed
        // TODO add your handling code here:
        SQL("DELETE FROM mahasiswa WHERE id ="+this.id+"");
        load_table("");
        kosong();
    }//GEN-LAST:event_B_HapusActionPerformed

    private void B_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CariActionPerformed
        // TODO add your handling code here:
        String cari = TF_Cari.getText();
        load_table("SELECT * FROM mahasiswa WHERE nim LIKE '%"+cari+"%' OR nama LIKE '%"+cari+"%'");
        
    }//GEN-LAST:event_B_CariActionPerformed

    private void TF_CariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_CariKeyReleased
        // TODO add your handling code here:
        String cari = TF_Cari.getText();
        load_table("SELECT * FROM mahasiswa WHERE nim LIKE '%"+cari+"%' OR nama LIKE '%"+cari+"%'");
    }//GEN-LAST:event_TF_CariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Input_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Input_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Input_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Input_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Input_Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Cari;
    private javax.swing.JButton B_Edit;
    private javax.swing.JButton B_Hapus;
    private javax.swing.JButton B_Input;
    private javax.swing.JTextField TF_Cari;
    private javax.swing.JTextField TF_NIM;
    private javax.swing.JTextField TF_Nama;
    private javax.swing.JTextField TF_NilaiHarian;
    private javax.swing.JTextField TF_NilaiUAS;
    private javax.swing.JTextField TF_NilaiUTS;
    private javax.swing.JTable Table_Mahasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
